tercera_preentrega_app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'tercera_preentrega_app'

urlpatterns = [
    path('', views.login_request, name='login'),
    path('acerca_de/', views.acerca_de, name='acerca_de'),
    path('perfil/', views.perfil, name='perfil'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('videojuegos/', views.lista_videojuegos, name='lista_videojuegos'),
    path('videojuego/<int:pk>/', views.detalle_videojuego, name='detalle_videojuego'),
    path('videojuego/<int:pk>/editar/', views.editar_videojuego, name='editar_videojuego'),
    path('videojuego/<int:pk>/eliminar/', views.eliminar_videojuego, name='eliminar_videojuego'),
    path('consolas/', views.lista_consolas, name='lista_consolas'),
    path('consola/<int:pk>/', views.detalle_consola, name='detalle_consola'),
    path('consola/<int:pk>/editar', views.editar_consola, name='editar_consola'),
    path('consola/<int:pk>/eliminar', views.eliminar_consola, name='eliminar_consola'),
    path('accesorios/', views.lista_accesorios, name='lista_accesorios'),
    path('accesorio/<int:pk>/', views.detalle_accesorio, name='detalle_accesorio'),
    path('accesorio/<int:pk>/editar', views.editar_accesorio, name='editar_accesorio'),
    path('accesorio/<int:pk>/eliminar', views.eliminar_accesorio, name='eliminar_accesorio'),
    path('buscar/', views.buscar, name='buscar'),
    path('registro/', views.register, name='registro'),
    path('logout', LogoutView.as_view(template_name='tercera_preentrega_app/logout.html'), name='logout'),
]

tercera_preentrega_chazarreta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tercera_preentrega_app.urls')),
]

# Para imágenes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tercera_preentrega_app/models.py
from django.contrib.auth.models import User
from django.db import models

def user_directory_path(instance, filename):
    # El archivo se subirá a MEDIA_ROOT/user_<id>/<filename>
    return f'user_{instance.user.id}/{filename}'

class Videojuego(models.Model):
    titulo = models.CharField(max_length=200)
    genero = models.CharField(max_length=100)
    desarrollador = models.CharField(max_length=100)
    año_lanzamiento = models.PositiveIntegerField()

    def __str__(self):
        return self.titulo
    
    def get_tipo(self):
        return 'Videojuego'

class Consola(models.Model):
    nombre = models.CharField(max_length=100)
    fabricante = models.CharField(max_length=100)
    año_lanzamiento = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre
    
    def get_tipo(self):
        return 'Consola'

class Accesorio(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
    def get_tipo(self):
        return 'Accesorio'
    

class Review(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    videojuego = models.ForeignKey(Videojuego, on_delete=models.CASCADE, null=True, blank=True)
    consola = models.ForeignKey(Consola, on_delete=models.CASCADE, null=True, blank=True)
    accesorio = models.ForeignKey(Accesorio, on_delete=models.CASCADE, null=True, blank=True)
    calificacion = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.videojuego:
            return f'Reseña de {self.videojuego.titulo} por {self.usuario.username}'
        elif self.consola:
            return f'Reseña de {self.consola.nombre} por {self.usuario.username}'
        elif self.accesorio:
            return f'Reseña de {self.accesorio.nombre} por {self.usuario.username}'

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=user_directory_path, blank=True)

    def __str__(self):
        return self.user.username

tercera_preentrega_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Videojuego, Consola, Accesorio, Perfil, Review

class VideojuegoForm(forms.ModelForm):
    class Meta:
        model = Videojuego
        fields = ['titulo', 'desarrollador', 'genero', 'año_lanzamiento']

class ConsolaForm(forms.ModelForm):
    class Meta:
        model = Consola
        fields = ['nombre', 'fabricante', 'año_lanzamiento']

class AccesorioForm(forms.ModelForm):
    class Meta:
        model = Accesorio
        fields = ['nombre', 'tipo']

class BusquedaForm(forms.Form):
    OPCIONES_BUSQUEDA = [
        ('videojuego', 'Videojuego'),
        ('consola', 'Consola'),
        ('accesorio', 'Accesorio'),
    ]

    termino_busqueda = forms.CharField(label='Buscar', max_length=100)
    tipo_busqueda = forms.ChoiceField(label='Tipo de búsqueda', choices=OPCIONES_BUSQUEDA)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['calificacion', 'comentario']

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class UserRegisterForm(UserCreationForm):

    email = forms.EmailField()
    avatar = forms.ImageField(required=False)

    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'avatar']
        #Saca los mensajes de ayuda
        help_texts = {k:"" for k in fields}

    def save(self, commit=True):
        user = super().save(commit=False)

        if 'avatar' in self.cleaned_data and self.cleaned_data['avatar']:
            user.save()
            perfil = Perfil(user=user, avatar=self.cleaned_data['avatar'])
            perfil.save()
    
        if commit:
            user.save()
        
        return user
    
class EditarPerfilForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'avatar']
    
    avatar = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = ''  # Opcional: quitar el mensaje de ayuda

    def save(self, commit=True):
        user = super().save(commit=False)

        if 'avatar' in self.cleaned_data and self.cleaned_data['avatar']:
            perfil, created = Perfil.objects.get_or_create(user=user)
            perfil.avatar = self.cleaned_data['avatar']
            perfil.save()

        if commit:
            user.save()
        
        return user

tercera_preentrega_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required, user_passes_test

from .models import Videojuego, Consola, Accesorio, Review
from .forms import VideojuegoForm, ConsolaForm, AccesorioForm, BusquedaForm, ReviewForm, UserRegisterForm, EditarPerfilForm, LoginForm

def user_not_logged_in(user):
    return not user.is_authenticated

@login_required
def lista_videojuegos(request):
    videojuegos = Videojuego.objects.all()
    form = VideojuegoForm()

    if request.method == 'POST':
        form = VideojuegoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tercera_preentrega_app:lista_videojuegos')


    return render(request, 'tercera_preentrega_app/lista_videojuegos.html', {'videojuegos': videojuegos, 'form': form})

@login_required
def detalle_videojuego(request, pk):
    videojuego = Videojuego.objects.get(pk=pk)
    review_form = ReviewForm()
    reviews = Review.objects.filter(videojuego=videojuego)

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.usuario = request.user
            review.videojuego = videojuego
            review.save()
            return redirect('tercera_preentrega_app:detalle_videojuego', pk=pk)
        
    return render(request, 'tercera_preentrega_app/detalle_videojuego.html', {'videojuego': videojuego, 'reviews': reviews, 'review_form': review_form})

@login_required
def editar_videojuego(request, pk):
    videojuego = get_object_or_404(Videojuego, pk=pk)

    if request.method == 'POST':
        form = VideojuegoForm(request.POST, instance=videojuego)
        if form.is_valid():
            form.save()
            return redirect('/videojuegos')
    else:
        form = VideojuegoForm(instance=videojuego)

    return render(request, 'tercera_preentrega_app/editar_videojuego.html', {'form': form})

@login_required
def eliminar_videojuego(request, pk):
    videojuego = get_object_or_404(Videojuego, pk=pk)

    if request.method == 'POST':
        videojuego.delete()
        return redirect('/videojuegos')

    return render(request, 'tercera_preentrega_app/eliminar_videojuego.html', {'videojuego': videojuego})

@login_required
def lista_consolas(request):
    consolas = Consola.objects.all()
    form = ConsolaForm()

    if request.method == 'POST':
        form = ConsolaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tercera_preentrega_app:lista_consolas')

    return render(request, 'tercera_preentrega_app/lista_consolas.html', {'consolas': consolas, 'form': form})

@login_required
def detalle_consola(request, pk):
    consola = Consola.objects.get(pk=pk)
    review_form = ReviewForm()
    reviews = Review.objects.filter(consola=consola)

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.usuario = request.user
            review.consola = consola
            review.save()
            return redirect('tercera_preentrega_app:detalle_consola', pk=pk)
        
    return render(request, 'tercera_preentrega_app/detalle_consola.html', {'consola': consola, 'reviews': reviews, 'review_form': review_form})

@login_required
def editar_consola(request, pk):
    consola = get_object_or_404(Consola, pk=pk)

    if request.method == 'POST':
        form = ConsolaForm(request.POST, instance=consola)
        if form.is_valid():
            form.save()
            return redirect('/consolas')
    else:
        form = ConsolaForm(instance=consola)

    return render(request, 'tercera_preentrega_app/editar_consola.html', {'form': form})

@login_required
def eliminar_consola(request, pk):
    consola = get_object_or_404(Consola, pk=pk)

    if request.method == 'POST':
        consola.delete()
        return redirect('/consolas')

    return render(request, 'tercera_preentrega_app/eliminar_consola.html', {'consola': consola})

@login_required
def lista_accesorios(request):
    accesorios = Accesorio.objects.all()
    form = AccesorioForm()

    if request.method == 'POST':
        form = AccesorioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tercera_preentrega_app:lista_accesorios')

    return render(request, 'tercera_preentrega_app/lista_accesorios.html', {'accesorios': accesorios, 'form': form})

@login_required
def detalle_accesorio(request, pk):
    accesorio = Accesorio.objects.get(pk=pk)
    review_form = ReviewForm()
    reviews = Review.objects.filter(accesorio=accesorio)

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.usuario = request.user
            review.accesorio = accesorio
            review.save()
            return redirect('tercera_preentrega_app:detalle_accesorio', pk=pk)
        
    return render(request, 'tercera_preentrega_app/detalle_accesorio.html', {'accesorio': accesorio, 'reviews': reviews, 'review_form': review_form})

@login_required
def editar_accesorio(request, pk):
    accesorio = get_object_or_404(Accesorio, pk=pk)

    if request.method == 'POST':
        form = AccesorioForm(request.POST, instance=accesorio)
        if form.is_valid():
            form.save()
            return redirect('/accesorios')
    else:
        form = AccesorioForm(instance=accesorio)

    return render(request, 'tercera_preentrega_app/editar_accesorio.html', {'form': form})

@login_required
def eliminar_accesorio(request, pk):
    accesorio = get_object_or_404(Accesorio, pk=pk)

    if request.method == 'POST':
        accesorio.delete()
        return redirect('/accesorios')

    return render(request, 'tercera_preentrega_app/eliminar_accesorio.html', {'accesorio': accesorio})

@login_required
def buscar(request):
    if request.method == 'POST':
        form = BusquedaForm(request.POST)
        if form.is_valid():
            termino_busqueda = form.cleaned_data['termino_busqueda']
            tipo_busqueda = form.cleaned_data['tipo_busqueda']

            if tipo_busqueda == 'videojuego':
                resultados = Videojuego.objects.filter(titulo__icontains=termino_busqueda)
            elif tipo_busqueda == 'consola':
                resultados = Consola.objects.filter(nombre__icontains=termino_busqueda)
            else:
                resultados = Accesorio.objects.filter(nombre__icontains=termino_busqueda)

            return render(request, 'tercera_preentrega_app/resultados_busqueda.html', {'resultados': resultados, 'tipo_busqueda': tipo_busqueda, 'termino_busqueda': termino_busqueda})

    else:
        form = BusquedaForm()

    return render(request, 'tercera_preentrega_app/buscar.html', {'form': form})

@user_passes_test(user_not_logged_in, login_url='tercera_preentrega_app:lista_videojuegos')
def login_request(request):
    if request.method == 'POST':
        form = LoginForm(request, data = request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contra = form.cleaned_data.get('password')

            user = authenticate(username=usuario, password=contra)

            if user is not None:
                login(request, user)

                return redirect('/perfil')
        
    form = LoginForm()

    return render(request, 'tercera_preentrega_app/login.html', {'form':form})

@user_passes_test(user_not_logged_in, login_url='tercera_preentrega_app:lista_videojuegos')
def register(request):

    if request.method == 'POST':

        form = UserRegisterForm(request.POST, request.FILES)
        
        if form.is_valid():

            username = form.cleaned_data['username']
            form.save()
            return redirect('/', {"mensaje": "Usuario Creado, Bienvenido/a "+ username})
        
    else:
        form = UserRegisterForm()

    return render(request, 'tercera_preentrega_app/registro.html', {"form": form})

@login_required
def perfil(request):
    usuario = request.user
    return render(request, 'tercera_preentrega_app/perfil.html', {'usuario': usuario})

@login_required
def editar_perfil(request):
    usuario = request.user

    if request.method == 'POST':
        form = EditarPerfilForm(request.POST, request.FILES, instance=usuario)
        
        if form.is_valid():
            form.save()
            return redirect('/perfil')
    else:
        form = EditarPerfilForm(instance=usuario)

    return render(request, 'tercera_preentrega_app/editar_perfil.html', {'usuario': usuario, 'form': form})

def acerca_de(request):
    return render(request, 'tercera_preentrega_app/acerca_de.html')

def page_not_found(request, exception):
    return render(request, '404.html', status=404)

tercera_preentrega_app/templates/tercera_preentrega_app/base.html
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}Mi Sitio{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'tercera_preentrega_app/css/style.css' %}" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous" />
</head>

<body>
  <header>
    <h1>
      El Rincón del Gamer
    </h1>
    <img class="logo" src="{% static 'tercera_preentrega_app/assets/logo.png' %}" alt="logo">
  </header>

  {% if user.is_authenticated %}
  <nav>
    <ul class="navbar-left">
      <li>
        <a href="{% url 'tercera_preentrega_app:lista_videojuegos' %}">Videojuegos</a>
      </li>
      <li>
        <a href="{% url 'tercera_preentrega_app:lista_consolas' %}">Consolas</a>
      </li>
      <li>
        <a href="{% url 'tercera_preentrega_app:lista_accesorios' %}">Accesorios</a>
      </li>
      <li>
        <a href="{% url 'tercera_preentrega_app:buscar' %}">Buscar</a>
      </li>
    </ul>
    <div class="navbar-right">
      <a class="navbar-link-img" href="{% url 'tercera_preentrega_app:perfil' %}">
        {% if usuario.perfil.avatar.url %}
        <img src="{{ usuario.perfil.avatar.url }}" alt="avatar">
        {% else %}
        <img src="{% static 'tercera_preentrega_app/assets/img-perfil.png' %}" alt="avatar por defecto">
        {% endif %}
      </a>
      <a href="{% url 'tercera_preentrega_app:logout' %}">Cerrar sesión</a>
    </div>
  </nav>
  {% endif %}

  <main>
    {% block content %}
    <!-- Aquí va el contenido específico de cada página -->
    {% endblock %}
  </main>

  <footer>
    <p><a href="{% url 'tercera_preentrega_app:acerca_de' %}">Gabriel
        Chazarreta</a> &copy; 2023 - El
      Rincón del Gamer</p>
  </footer>

  <script src="{% static 'tercera_preentrega_app/js/index.js' %}"></script>
</body>

</html>

tercera_preentrega_app/templates/tercera_preentrega_app/buscar.html
{% extends "tercera_preentrega_app/base.html" %}
{% load static %}

{% block title %}Buscar{% endblock %}

{% block content %}
<h1>Buscar</h1>
<form action="{% url 'tercera_preentrega_app:buscar' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Buscar</button>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/detalle_consola.html
{% extends "tercera_preentrega_app/base.html" %}
{% load static %}
{% block title %}Detalle de Consola{% endblock %}
{% block content %}
<h1>Detalle de Consola</h1>
<p>Nombre: {{ consola.nombre }}</p>
<p>Fabricante: {{ consola.fabricante }}</p>
<p>Año de Lanzamiento: {{ consola.año_lanzamiento }}</p>

<h2>Reseñas</h2>
{% if reviews %}
<ul>
    {% for review in reviews %}
    <li>
        <div>
            <p>{{ review.usuario.username }}</p>
        </div>
        <div>
            {{ review.comentario }} - {{ review.calificacion }}
        </div>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No se han agregado reseñas aún.</p>
{% endif %}

<div class="form-container">
    <h2>Agregar Reseña</h2>
    <form method="post">
        {% csrf_token %}
        {{ review_form.as_p }}
        <button type="submit">Agregar Reseña</button>
    </form>
</div>

<div>
    <a href="{% url 'tercera_preentrega_app:lista_consolas' %}" class="btn btn-primary">Volver atrás</a>
</div>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/detalle_videojuego.html
{% extends "tercera_preentrega_app/base.html" %}
{% load static %}
{% block title %}Detalle de Videojuego{% endblock %}
{% block content %}
<h1>Detalle de Videojuego</h1>
<p>Título: {{ videojuego.titulo }}</p>
<p>Desarrollador: {{ videojuego.desarrollador }}</p>
<p>Género: {{ videojuego.genero }}</p>
<p>Año de Lanzamiento: {{ videojuego.año_lanzamiento }}</p>

<h2>Reseñas</h2>
{% if reviews %}
<ul>
    {% for review in reviews %}
    <div>
        <p>{{ review.usuario.username }}</p>
    </div>
    <div>
        {{ review.comentario }} - {{ review.calificacion }}
    </div>
    {% endfor %}
</ul>
{% else %}
<p>No se han agregado reseñas aún.</p>
{% endif %}

<div class="form-container">
    <h2>Agregar Reseña</h2>
    <form method="post">
        {% csrf_token %}
        {{ review_form.as_p }}
        <button type="submit">Agregar Reseña</button>
    </form>
</div>

<div>
    <a href="{% url 'tercera_preentrega_app:lista_videojuegos' %}" class="btn btn-primary">Volver atrás</a>
</div>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/editar_accesorio.html
{% extends 'tercera_preentrega_app/base.html' %}
{% block content %}
<h2>Editar Accesorio</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/editar_consola.html
{% extends 'tercera_preentrega_app/base.html' %}
{% block content %}
<h2>Editar Consola</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/editar_videojuego.html
{% extends 'tercera_preentrega_app/base.html' %}
{% block content %}
<h2>Editar Videojuego</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/eliminar_accesorio.html
{% extends 'tercera_preentrega_app/base.html' %}
{% block content %}
<h2>Eliminar Accesorio</h2>
<p>¿Estás seguro de que deseas eliminar el accesorio "{{ accesorio.nombre }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
    <a href="{% url 'tercera_preentrega_app:lista_accesorios' %}">Cancelar</a>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/eliminar_videojuego.html
{% extends 'tercera_preentrega_app/base.html' %}
{% block content %}
<h2>Eliminar Videojuego</h2>
<p>¿Estás seguro de que deseas eliminar el videojuego "{{ videojuego.titulo }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
    <a href="{% url 'tercera_preentrega_app:lista_videojuegos' %}">Cancelar</a>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/lista_accesorios.html
{% extends "tercera_preentrega_app/base.html" %}
{% load static %}
{% block title %}Lista de Accesorios{% endblock %}
{% block content %}
<h1>Lista de Accesorios</h1>
<div class="container">
  <ul>
    {% for accesorio in accesorios %}
    <li>
      <a href="{% url 'tercera_preentrega_app:detalle_accesorio' accesorio.id %}">
        {{ accesorio.nombre }}
      </a>
      <span class="container-actions">
        <a href="{% url 'tercera_preentrega_app:editar_accesorio' accesorio.id %}">
          <i class="fas fa-edit"></i>
        </a>
        <a href="{% url 'tercera_preentrega_app:eliminar_accesorio' accesorio.id %}">
          <i class="fas fa-trash"></i>
        </a>
      </span>
    </li>
    {% endfor %}
  </ul>
  <div class="image-container">
    <img src="{% static 'tercera_preentrega_app/assets/accesorio.png' %}" alt="accesorio" />
  </div>
</div>

<h2>Agregar nuevo accesorio</h2>
<form action="" method="POST" id="miFormulario">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/lista_consolas.html
{% extends "tercera_preentrega_app/base.html" %}
{% load static %}
{% block title %}Lista de Consolas{% endblock %}
{% block content %}
<h1>Lista de Consolas</h1>
<div class="container">
  <ul>
    {% for consola in consolas %}
    <li>
      <a href="{% url 'tercera_preentrega_app:detalle_consola' consola.id %}">
        {{ consola.nombre }} - {{ consola.fabricante }}
      </a>
      <span class="container-actions">
        <a href="{% url 'tercera_preentrega_app:editar_consola' consola.id %}">
          <i class="fas fa-edit"></i>
        </a>
        <a href="{% url 'tercera_preentrega_app:eliminar_consola' consola.id %}">
          <i class="fas fa-trash"></i>
        </a>
      </span>
    </li>
    {% endfor %}
  </ul>
  <div class="image-container">
    <img src="{% static 'tercera_preentrega_app/assets/consola.png' %}" alt="consola" />
  </div>
</div>

<h2>Agregar nueva consola</h2>
<form action="" method="POST" id="miFormulario">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/logout.html
{% extends 'tercera_preentrega_app/base.html' %}
{% block content %}
<h2>Cierre de sesión</h2>
<p>Cerraste sesión correctamente. Hasta pronto!</p>
<div class="link-login">
    <a href="{% url 'tercera_preentrega_app:login' %}">Ir a Inicio</a>
</div>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/perfil.html
{% extends 'tercera_preentrega_app/base.html' %}
{% load static %}

{% block content %}
<h2 class="profile-heading">¡Bienvenido, {{ usuario.username }}!</h2>
<div class="profile-image">
    <p>Foto de perfil</p>
    {% if usuario.perfil.avatar.url %}
    <img src="{{ usuario.perfil.avatar.url }}" alt="avatar" class="avatar-image">
    {% else %}
    <img src="{% static 'tercera_preentrega_app/assets/img-perfil.png' %}" alt="avatar por defecto"
        class="avatar-image">
    {% endif %}
</div>
<p class="profile-info">Tu información:</p>
<ul class="profile-list">
    <li>Nombre de usuario: {{ usuario.username }}</li>
    <li>Email: {{ usuario.email }}</li>
</ul>
<a href="{% url 'tercera_preentrega_app:editar_perfil' %}" class="btn btn-primary">Actualizar Perfil</a>
{% endblock %}

tercera_preentrega_app/templates/tercera_preentrega_app/registro.html
{% extends 'tercera_preentrega_app/base.html' %}
{% block content %}
<h2>Registrarse</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.username.label_tag }} {{ form.username }}
        <span class="form-error">{{ form.username.errors }}</span>
    </div>
    <div>
        {{ form.email.label_tag }} {{ form.email }}
        <span class="form-error">{{ form.email.errors }}</span>
    </div>
    <div>
        {{ form.password1.label_tag }} {{ form.password1 }}
        <span class="form-error">{{ form.password1.errors }}</span>
    </div>
    <div>
        {{ form.password2.label_tag }} {{ form.password2 }}
        <span class="form-error">{{ form.password2.errors }}</span>
    </div>
    <div>
        {{ form.avatar.label_tag }} {{ form.avatar }}
        <span class="form-error">{{ form.avatar.errors }}</span>
    </div>
    <div class="container-btn">
        <button type="submit" class="btn-primary">Registrarse</button>
    </div>
</form>
<div class="link-login">
    <a href="{% url 'tercera_preentrega_app:login' %}">¿Ya tienes una cuenta? Inicia sesión.</a>
</div>
{% endblock %}